#!/bin/bash

color='\033[1;31m'
nc='\033[0m'
ip=$1
echo -e "\n${color}starting stage 1 with TCP scan.${nc}\n"
sudo nmap -Pn -sS --stats-every 3m --max-retries 1 --max-scan-delay 20 --defeat-rst-ratelimit -T4 -p-65535 -oN ./$ip.txt $ip
p=$(cat localhost.txt | grep tcp | cut -d '/' -f 1 | tr '\n' ',') && port=$(echo ${p::-1})
echo -e "\n${color}Completed Stage 1 and Initiating stage 2 with UDP scan.${nc}\n"
sudo nmap -Pn --top-ports 1000 -sU --stats-every 3m --max-retries 1 -T3 -oN ./$ip_UDP.txt $ip
echo -e "\n${color}Starting the detailed scan of Identified TCP Ports.${nc}\n"
sudo nmap -nvv -Pn- -sSV -p $port --version-intensity 9 -A -oN ./$ip_tcp_detailed.txt $ip
echo -e "\n${color}Nmap scan has been successfully completed.${nc}\n"
